#!/bin/bash

collections=(user farm market_day_booth product_detail)

for coll in ${collections[*]}
do
    mongoimport --db freshquest --collection $coll --drop --stopOnError < $coll.mongoexport
done

